In [1]:
import pandas as pd
import numpy as np
import dtale
import seaborn as sns
import matplotlib.pyplot as plt
import sklearn

In [2]:
red=pd.read_csv('winequality-red.csv',sep=';')
white=pd.read_csv('winequality-white.csv',sep=';')

In [3]:
red.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [4]:
white.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6  
3      9.9        6  
4      9.9        6

In [5]:
red.columns = [x.strip().replace(' ','_') for x in red.columns]
red.head()

fixed_acidity  volatile_acidity  citric_acid  residual_sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free_sulfur_dioxide  total_sulfur_dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [6]:
white.columns = [x.strip().replace(' ','_') for x in white.columns]
white.head()

fixed_acidity  volatile_acidity  citric_acid  residual_sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free_sulfur_dioxide  total_sulfur_dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6  
3      9.9        6  
4      9.9        6

In [7]:
red['is_red']=1

In [8]:
red.head()

fixed_acidity  volatile_acidity  citric_acid  residual_sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free_sulfur_dioxide  total_sulfur_dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  is_red  
0      9.4        5       1  
1      9.8        5       1  
2      9.8        5       1  
3      9.8        6       1  
4      9.4        5       1

In [9]:
white['is_red']=0
white.head()

fixed_acidity  volatile_acidity  citric_acid  residual_sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free_sulfur_dioxide  total_sulfur_dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  is_red  
0      8.8        6       0  
1      9.5        6       0  
2     10.1        6       0  
3      9.9        6       0  
4      9.9        6       0

In [10]:
df=pd.concat([red,white],ignore_index=True)
df.describe()

fixed_acidity  volatile_acidity  citric_acid  residual_sugar  \
count    6497.000000       6497.000000  6497.000000     6497.000000   
mean        7.215307          0.339666     0.318633        5.443235   
std         1.296434          0.164636     0.145318        4.757804   
min         3.800000          0.080000     0.000000        0.600000   
25%         6.400000          0.230000     0.250000        1.800000   
50%         7.000000          0.290000     0.310000        3.000000   
75%         7.700000          0.400000     0.390000        8.100000   
max        15.900000          1.580000     1.660000       65.800000   

         chlorides  free_sulfur_dioxide  total_sulfur_dioxide      density  \
count  6497.000000          6497.000000           6497.000000  6497.000000   
mean      0.056034            30.525319            115.744574     0.994697   
std       0.035034            17.749400             56.521855     0.002999   
min       0.009000             1.000000              6.000000     0.987110   
25%       0.038000            17.000000             77.000000     0.992340   
50%       0.047000            29.000000            118.000000     0.994890   
75%       0.065000            41.000000            156.000000     0.996990   
max       0.611000           289.000000            440.000000     1.038980   

                pH    sulphates      alcohol      quality       is_red  
count  6497.000000  6497.000000  6497.000000  6497.000000  6497.000000  
mean      3.218501     0.531268    10.491801     5.818378     0.246114  
std       0.160787     0.148806     1.192712     0.873255     0.430779  
min       2.720000     0.220000     8.000000     3.000000     0.000000  
25%       3.110000     0.430000     9.500000     5.000000     0.000000  
50%       3.210000     0.510000    10.300000     6.000000     0.000000  
75%       3.320000     0.600000    11.300000     6.000000     0.000000  
max       4.010000     2.000000    14.900000     9.000000     1.000000

In [11]:
dtale.show(red)

In [12]:
X=red.drop('quality',axis=1)

In [13]:
X.head()

fixed_acidity  volatile_acidity  citric_acid  residual_sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free_sulfur_dioxide  total_sulfur_dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  is_red  
0      9.4       1  
1      9.8       1  
2      9.8       1  
3      9.8       1  
4      9.4       1

In [14]:
y=red['quality']
y.head()

0    5
1    5
2    5
3    6
4    5
Name: quality, dtype: int64

In [15]:
from sklearn import model_selection
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [16]:
X_train,X_test,y_train,y_test=model_selection.train_test_split(X,y,test_size=0.25)

In [17]:
linear_reg_pipeline=Pipeline([('Scalar',StandardScaler()),('PCA',PCA(n_components=4)),('Linear_Regression',LogisticRegression())])
linear_reg_pipeline.fit(X_train,y_train)
linear_reg_pipeline.score(X_test,y_test)

0.5925

In [18]:
random_forest_pipeline=Pipeline([('Scalar',StandardScaler()),('PCA',PCA(n_components=5)),('Random_forest',RandomForestClassifier(n_estimators=25))])
random_forest_pipeline.fit(X_train,y_train)
random_forest_pipeline.score(X_test,y_test)

0.7025

In [19]:
df.isnull().sum()

fixed_acidity           0
volatile_acidity        0
citric_acid             0
residual_sugar          0
chlorides               0
free_sulfur_dioxide     0
total_sulfur_dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
is_red                  0
dtype: int64

In [20]:
linear_reg_pipeline=Pipeline([('Scalar',StandardScaler()),('PCA',PCA(n_components=4)),('Linear_Regression',LinearRegression())])
linear_reg_pipeline.fit(X_train,y_train)
linear_reg_pipeline.score(X_test,y_test)

0.34984248762369097

In [21]:
poly = PolynomialFeatures(degree = 2, interaction_only=False, include_bias=False)

lr = LogisticRegression(max_iter=1000)

pipe = Pipeline([('polynomial_features',poly), ('Scalar',StandardScaler()),('PCA',PCA(n_components=32)),('logistic_regression',lr)])
pipe.fit(X_train, y_train)
pipe.score(X_test, y_test)

0.605

In [22]:
poly = PolynomialFeatures(degree = 2, interaction_only=False, include_bias=False)

lr = LogisticRegression(max_iter=1000)

pipe = Pipeline([('polynomial_features',poly), ('Scalar',StandardScaler()),('PCA',PCA(n_components=32)),('Random_forest',RandomForestClassifier(n_estimators=25))])
pipe.fit(X_train, y_train)
pipe.score(X_test, y_test)

0.73

In [23]:
x_poly=poly.fit_transform(X_train)

In [24]:
x_poly.shape

(1199, 90)

In [25]:
X_train.shape

(1199, 12)

In [26]:
X_train.describe(include='all')

fixed_acidity  volatile_acidity  citric_acid  residual_sugar  \
count    1199.000000       1199.000000  1199.000000     1199.000000   
mean        8.311760          0.531122     0.269783        2.500083   
std         1.736071          0.180154     0.197256        1.327744   
min         4.900000          0.120000     0.000000        1.200000   
25%         7.100000          0.400000     0.090000        1.900000   
50%         7.900000          0.520000     0.250000        2.200000   
75%         9.200000          0.635000     0.420000        2.600000   
max        15.600000          1.580000     1.000000       15.400000   

         chlorides  free_sulfur_dioxide  total_sulfur_dioxide      density  \
count  1199.000000          1199.000000           1199.000000  1199.000000   
mean      0.087339            15.773561             46.235613     0.996741   
std       0.047815            10.435839             32.752406     0.001871   
min       0.012000             1.000000              6.000000     0.990200   
25%       0.070000             7.000000             21.000000     0.995590   
50%       0.079000            14.000000             37.000000     0.996760   
75%       0.090000            21.000000             62.000000     0.997845   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates      alcohol  is_red  
count  1199.000000  1199.000000  1199.000000  1199.0  
mean      3.312702     0.655304    10.416597     1.0  
std       0.152971     0.168364     1.053364     0.0  
min       2.740000     0.330000     8.400000     1.0  
25%       3.210000     0.550000     9.500000     1.0  
50%       3.310000     0.620000    10.100000     1.0  
75%       3.400000     0.730000    11.100000     1.0  
max       3.900000     2.000000    14.000000     1.0

In [27]:
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
rf=RandomForestClassifier(n_estimators=100,random_state=42)
rf.fit(X_train,y_train)
predrf=rf.predict(X_test)
print(metrics.accuracy_score(predrf,y_test))
print(metrics.confusion_matrix(predrf,y_test))
print(metrics.classification_report(predrf,y_test))

0.6975
[[  0   0   0   0   0   0]
 [  1   0   0   0   0   0]
 [  1   6 137  29   2   0]
 [  0   5  31 119  26   4]
 [  0   0   1  10  22   4]
 [  0   0   0   0   1   1]]
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         0
           4       0.00      0.00      0.00         1
           5       0.81      0.78      0.80       175
           6       0.75      0.64      0.69       185
           7       0.43      0.59      0.50        37
           8       0.11      0.50      0.18         2

    accuracy                           0.70       400
   macro avg       0.35      0.42      0.36       400
weighted avg       0.74      0.70      0.72       400



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning:

Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.



In [28]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn import metrics
ad=AdaBoostClassifier(n_estimators=100,random_state=42)
ad.fit(X_train,y_train)
predrf=ad.predict(X_test)
print(metrics.accuracy_score(predrf,y_test))
print(metrics.confusion_matrix(predrf,y_test))
print(metrics.classification_report(predrf,y_test))

0.5675
[[  0   0   0   0   0   0]
 [  0   2   6   1   0   0]
 [  2   5 112  44   2   0]
 [  0   4  47  95  31   6]
 [  0   0   4  16  18   3]
 [  0   0   0   2   0   0]]
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         0
           4       0.18      0.22      0.20         9
           5       0.66      0.68      0.67       165
           6       0.60      0.52      0.56       183
           7       0.35      0.44      0.39        41
           8       0.00      0.00      0.00         2

    accuracy                           0.57       400
   macro avg       0.30      0.31      0.30       400
weighted avg       0.59      0.57      0.58       400



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning:

Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.



In [29]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn import metrics
ad=AdaBoostClassifier(n_estimators=4)
ad.fit(X_train,y_train)
predrf=ad.predict(X_test)
print(metrics.accuracy_score(predrf,y_test))
print(metrics.confusion_matrix(predrf,y_test))
print(metrics.classification_report(predrf,y_test))

0.5575
[[  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  2   7 121  56   5   0]
 [  0   4  48 102  46   9]
 [  0   0   0   0   0   0]
 [  0   0   0   0   0   0]]
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         0
           4       0.00      0.00      0.00         0
           5       0.72      0.63      0.67       191
           6       0.65      0.49      0.56       209
           7       0.00      0.00      0.00         0
           8       0.00      0.00      0.00         0

    accuracy                           0.56       400
   macro avg       0.23      0.19      0.20       400
weighted avg       0.68      0.56      0.61       400



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning:

Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.



In [30]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.svm import SVC
sv=SVC()
from sklearn import metrics
ad=AdaBoostClassifier(base_estimator=sv,n_estimators=100,random_state=42,algorithm='SAMME')
ad.fit(X_train,y_train)
predrf=ad.predict(X_test)
print(metrics.accuracy_score(predrf,y_test))
print(metrics.confusion_matrix(predrf,y_test))
print(metrics.classification_report(predrf,y_test))

0.4225
[[  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  2  11 169 158  51   9]
 [  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  0   0   0   0   0   0]]
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         0
           4       0.00      0.00      0.00         0
           5       1.00      0.42      0.59       400
           6       0.00      0.00      0.00         0
           7       0.00      0.00      0.00         0
           8       0.00      0.00      0.00         0

    accuracy                           0.42       400
   macro avg       0.17      0.07      0.10       400
weighted avg       1.00      0.42      0.59       400



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning:

Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.



In [31]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.svm import SVC
sv=SVC(probability=True,kernel='linear')
from sklearn import metrics
ad=AdaBoostClassifier(base_estimator=sv,n_estimators=100,random_state=42,algorithm='SAMME')
ad.fit(X_train,y_train)
predrf=ad.predict(X_test)
print(metrics.accuracy_score(predrf,y_test))
print(metrics.confusion_matrix(predrf,y_test))
print(metrics.classification_report(predrf,y_test))

0.51
[[  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  1   5  90  45   8   0]
 [  1   6  75 105  34   7]
 [  0   0   4   8   9   2]
 [  0   0   0   0   0   0]]
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         0
           4       0.00      0.00      0.00         0
           5       0.53      0.60      0.57       149
           6       0.66      0.46      0.54       228
           7       0.18      0.39      0.24        23
           8       0.00      0.00      0.00         0

    accuracy                           0.51       400
   macro avg       0.23      0.24      0.23       400
weighted avg       0.59      0.51      0.53       400



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning:

Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.



In [32]:
from sklearn.externals import joblib
joblib.dump(pipe,'PIPE.pkl')

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\externals\joblib\__init__.py:15: FutureWarning:

sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.



['PIPE.pkl']